Ensure PKCS11 config is at the top of openssl configuration

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -415,6 +415,27 @@ easyrsa_openssl() {
 	if [ -n "$PKCS11_PIN" ] && [ $pkcs11 ]; then
 		PKCS11_PIN_EXPANDED="PIN=${PKCS11_PIN}"
 	fi
+
+	if [ $pkcs11 ]; then
+		# Insert OpenSSL PKCS#11 Engine configuration first
+		cat > "$easyrsa_openssl_conf" << EOF
+openssl_conf = openssl_def
+
+[openssl_def]
+engines = engine_section
+
+[engine_section]
+pkcs11 = pkcs11_section
+
+[pkcs11_section]
+engine_id = pkcs11
+MODULE_PATH = ${PKCS11_MODULE_PATH}
+${PKCS11_PIN_EXPANDED}
+EOF
+		# Setup parameters to use OpenSSL Engine
+		openssl_pkcs11_params="-engine pkcs11 -keyform engine"
+	fi
+
 	# Make LibreSSL safe config file from OpenSSL config file
 	sed \
 		-e "s\`ENV::EASYRSA\`EASYRSA\`g" \
@@ -434,7 +455,7 @@ easyrsa_openssl() {
 		-e "s\`\$EASYRSA_REQ_CN\`$EASYRSA_REQ_CN\`g" \
 		-e "s\`\$EASYRSA_REQ_EMAIL\`$EASYRSA_REQ_EMAIL\`g" \
 		${EASYRSA_EXTRA_EXTS:+-e "/^#%EXTRA_EXTS%/r $easyrsa_extra_exts"} \
-		"$EASYRSA_SSL_CONF" > "$easyrsa_openssl_conf" ||
+		"$EASYRSA_SSL_CONF" >> "$easyrsa_openssl_conf" ||
 		die "Failed to update $easyrsa_openssl_conf"
   
 	# TODO: Consider using bash redirection to create file handles only readable by this process for temp files passed to openssl
@@ -443,24 +464,6 @@ easyrsa_openssl() {
 	if [ $pkcs11 ]; then
 		sed -i'' -e "s/=.*\/private\/ca.key/= label_$PKCS11_LABEL/g" "$easyrsa_openssl_conf" \
 			|| die "Failed to configure PKCS#11 token"
-
-		# Append OpenSSL Engine Configuration
-		cat >> "$easyrsa_openssl_conf" << EOF
-openssl_conf = openssl_def
-
-[openssl_def]
-engines = engine_section
-
-[engine_section]
-pkcs11 = pkcs11_section
-
-[pkcs11_section]
-engine_id = pkcs11
-MODULE_PATH = ${PKCS11_MODULE_PATH}
-${PKCS11_PIN_EXPANDED}
-EOF
-		# Setup parameters to use OpenSSL Engine
-		openssl_pkcs11_params="-engine pkcs11 -keyform engine"
 	fi
 
 	if [ "$openssl_command" = "makesafeconf" ]; then
@@ -704,7 +707,7 @@ current CA keypair. If you intended to start a new CA, run init-pki first."
 			printf "PKCS#11 Module Library: " && read -r PKCS11_MODULE_PATH
 		fi
 		if [ -z "$PKCS11_SLOT" ]; then
-			pkcs11-tool --module "$PKCS11_MODULE_PATH" --list-slots || die "unable to list slots using" "$PKCS11_MODULE_PATH"
+			easyrsa_pkcs11_tool --module "$PKCS11_MODULE_PATH" --list-slots || die "unable to list slots using" "$PKCS11_MODULE_PATH"
 			printf "PKCS#11 Slot ID (hex): " && read -r PKCS11_SLOT
 		fi
 		if [ -z "$PKCS11_LABEL" ]; then
