Verified renew works and a little more cleanup

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -341,9 +341,9 @@ cleanup() {
 } # => cleanup()
 
 debug() {
-	red=`tput setaf 1`
-	green=`tput setaf 3`
-	reset=`tput sgr0`
+	red=$(tput setaf 1)
+	green=$(tput setaf 3)
+	reset=$(tput sgr0)
 
 	echo -e "${red}DEBUG: ${green}[$(caller)]${red}" "$@" "${reset}" > /dev/stderr
 }
@@ -362,14 +362,9 @@ easyrsa_pkcs11_tool() {
 }
 
 easyrsa_openssl() {
-	#TODO: "Determine if we can put the pkcs11 configuration in easyrsa_openssl"
 	debug "openssl" "$@"
 	openssl_command=$1; shift
 
-	if [ "$PKCS11_MODULE_PATH" ] || [ $pkcs11 ]; then
-		KEY_IN_ENGINE=1
-		debug "Assuming PKCS#11 Usage"
-	fi
 	case $openssl_command in
 		makesafeconf) has_config=true;;
 		ca|req|srp|ts) has_config=true;;
@@ -417,38 +412,32 @@ easyrsa_openssl() {
 		"$EASYRSA_SSL_CONF" > "$easyrsa_openssl_conf" ||
 		die "Failed to update $easyrsa_openssl_conf"
   
+	# TODO: Include the PIN in the openssl config
+	# TODO: Consider using bash redirection to create file handles only readable by this process for temp files passed to openssl
+	#       This will be important if we really want to put the PIN in the config so there isn't a chance of it leaking.
+
 	# Question, should we just always look at the key file if we're here?
 	# If PKCS11_MODULE is not specified, it's probably in the key file where the pointers for the key are
-	debug "PKCS11_MODULE=" "$PKCS11_MODULE"
 	if [ -z "$PKCS11_MODULE" ]; then
-		debug "Attempting to read key file"
-		set -x
 		# Find the private key file
 		ca_key_file=$( sed -n "s/private_key\s*=\s*\(.*\)\s*#.*$/\1/p" "$easyrsa_openssl_conf" | xargs echo )
-		
 		# Check to see that it exists
 		if [ -f "$ca_key_file" ]; then
 			grep PRIVATE "$ca_key_file"
-			is_key=$?
-			if ! $is_key; then
-				debug "Sourcing" "$ca_key_file"
+			is_pkcs11_config=$?
+			# If the file isn't an actual key, let's source it! (TODO: implement same method as vars file for loading config?)
+			if [ $is_pkcs11_config -eq 1 ]; then
 				. "$ca_key_file"
 			fi
 		fi
-		
-		set +x
-		
 	fi
-
+	
 	if [ -n "$PKCS11_LABEL" ]; then
-	  set -x
 		#cat $easyrsa_openssl_conf
 		sed -i'' -e "s/=.*\/private\/ca.key/= label_$PKCS11_LABEL/g" "$easyrsa_openssl_conf" \
 			|| die "Failed to configure PKCS#11 token"
-		set +x
-				# Setup parameters to point to the appropriate key
+		# Setup parameters to point to the appropriate key
 		openssl_pkcs11_params="-engine pkcs11 -keyform engine"
-
 	fi
 
 	if [ "$openssl_command" = "makesafeconf" ]; then
@@ -456,12 +445,10 @@ easyrsa_openssl() {
 		err=$?
 	else
 		debug "Actual: " "$EASYRSA_OPENSSL" "$openssl_command" -config "$easyrsa_openssl_conf" $openssl_pkcs11_params "$@"
-		set -x
 		"$EASYRSA_OPENSSL" "$openssl_command" -config "$easyrsa_openssl_conf" $openssl_pkcs11_params "$@"
 		err=$?
-		set +x
 	fi
-	#read -r TEST
+
 	rm -f "$easyrsa_openssl_conf"
 	rm -f "$easyrsa_extra_exts"
 	return $err
@@ -560,9 +547,6 @@ $help_note"
 	# When operating in 'test' mode, return success.
 	# test callers don't care about CA-specific dir structure
 	[ "$1" = "test" ] && return 0
-
-
-	#TODO: "If operating a pkcs11 based ca, check the smartcard to make sure it's present and working"
 
 	# verify expected CA-specific dirs:
 	for i in issued certs_by_serial
@@ -665,7 +649,6 @@ If you intended to start a new CA, run init-pki first."
 
 	# If a private key exists here, a sub-ca was created but not signed.
 	# Notify the user and require a signed ca.crt or a init-pki:
-	#TODO: "add support to init_pki to clear an object in a PKCS#11 device"
 	[ -f "$out_key" ] && \
 		die "\
 A CA private key exists but no ca.crt is found in your PKI dir of:
@@ -692,21 +675,20 @@ current CA keypair. If you intended to start a new CA, run init-pki first."
 	out_file_tmp="$(easyrsa_mktemp)" || die "Failed to create temporary file"
 
 	if [ $pkcs11 ]; then
-		# TODO: PKCS11 build-ca parameters on command line
 		# Prepare parameters for PKCS11
 		echo "easy-rsa stores the key specific configuration in the appropriate key file and will not store sensitive information"
-		if [ -z $PKCS11_MODULE_PATH ]; then
+		if [ -z "$PKCS11_MODULE_PATH" ]; then
 			printf "PKCS#11 Module Library: " && read -r PKCS11_MODULE_PATH
 		fi
-		if [ -z $PKCS11_SLOT ]; then
-			pkcs11-tool --module $PKCS11_MODULE_PATH --list-slots || die "unable to list slots using $PKCS11_MODULE_PATH"
+		if [ -z "$PKCS11_SLOT" ]; then
+			pkcs11-tool --module "$PKCS11_MODULE_PATH" --list-slots || die "unable to list slots using" "$PKCS11_MODULE_PATH"
 			printf "PKCS#11 Slot ID (hex): " && read -r PKCS11_SLOT
 		fi
-		if [ -z $PKCS11_LABEL ]; then
+		if [ -z "$PKCS11_LABEL" ]; then
 			#TODO: "Validate PKCS11_LABEL otherwise a segfault is appearing"
 			printf "PKCS#11 Object Label: " && read -r PKCS11_LABEL
 		fi
-		if [ -z $PKCS11_PIN ]; then
+		if [ -z "$PKCS11_PIN" ]; then
 			printf "PKCS#11 PIN: " && hide_read_pass PKCS11_PIN
 		fi
 		
@@ -741,8 +723,8 @@ current CA keypair. If you intended to start a new CA, run init-pki first."
 			die "Unsupported \$EASYRSA_ALGO=$EASYRSA_ALGO"
 		fi
 		
-		easyrsa_pkcs11_tool --keypairgen --key-type $KEY_TYPE \
-							--label $PKCS11_LABEL \
+		easyrsa_pkcs11_tool --keypairgen --key-type "$KEY_TYPE" \
+							--label "$PKCS11_LABEL" \
 							--usage-sign \
 							--private
 							# TODO: figure out how to determine if the --sensitive flag is available on pkcs11-tool  
@@ -905,7 +887,6 @@ key: $key_out
 
 # common signing backend
 sign_req() {
-	#TODO: "add pkcs#11 support for sign-req command"
 	crt_type="$1"
 	opts=""
 	req_in="$EASYRSA_PKI/reqs/$2.req"
@@ -1008,7 +989,6 @@ Failed to create temp extension file (bad permissions?) at:
 $ext_tmp"
 	cat "$ext_tmp"
 	# sign request
-	# TODO: PKCS11 support for signing operations
 	crt_out_tmp="$(easyrsa_mktemp)" || die "Failed to create temporary file"
 	easyrsa_openssl ca -utf8 -in "$req_in" -out "$crt_out_tmp" \
 		-extfile "$ext_tmp" -days "$EASYRSA_CERT_EXPIRE" -batch $opts ${EASYRSA_PASSIN:+-passin "$EASYRSA_PASSIN"} \
@@ -1185,7 +1165,6 @@ input in file: $req_in"
 
 # renew backend
 renew() {
-	##TODO: "Ensure PKCS#11 support works with renew command"
 	verify_ca_init
 
 	# pull filename base:
